### ISSUE TITLE
Create and gather portfolio contents (text and visuals)

### ISSUE THREAD

**Issue by esclapes** [esclapes/esclapes.github.com#2]

**Comment by esclapes** [comment]
A personal brand website for @judithjanssen - https://judithjanssen.es/ 

What I learnt
- Personal Branding: define key messaging without being to general but giving room to different activities.
- First jekyll site: composed one-page landings, multilingual tweaks, hosted on GitHub Pages with the built in sass preprocessing.
- First stripe integration: simple checkout using [heroku-stripe-checkout ](https://github.com/esclapes/heroku-stripe-checkout) on the backen and [uptime robot](https://uptimerobot.com/) monitoring.
- Simple Free SSL and caching powered by [CloudFlare](https://www.cloudflare.com/ssl/)

What is pending:
- [Prose](http://prose.io/) integration for easier content creation.

**Comment by esclapes** [comment]
Webapp for easy bulk orders management for small food producers and food coops: foodhub.es [repo](https://github.com/esclapes/foodhub.es)

What I am learning (in progress, not yet live):
- MVP definition, just focus on order ux (oreder management and collection) and real clients (I already have somebody waiting for this)
- Better paper prototyping tool
- First Laravel 5.2 app with unit testing
- Getting my head around the react-redux app architecture, although I ended up using vue.js
- Using npm scripts as main dev/build tool

What is pending:
- Use vuex for vue state management
- Order management views.
- Ship it.

![mobile-paper-protoype](https://cloud.githubusercontent.com/assets/829971/14882596/d22284b2-0d39-11e6-8cd5-53f5bd66bb66.jpg)

**Comment by judithjanssen** [comment]
Retomar la foto.

On 28 April 2016 at 12:07, Eduardo Esclapés notifications@github.com
wrote:

> Webapp for easy bulk orders management for small food producers and food
> coops: foodhub.es repo https://github.com/esclapes/foodhub.es
> 
> What I am learning (in progress, not yet live):
> - MVP definition, just focus on order ux (oreder management and
>   collection) and real clients (I already have somebody waiting for this)
> - Better paper prototyping tool
> - First Laravel 5.2 app
> - Getting my head around the react-redux app architecture, although I
>   ended up using vue.js
> - Using npm scripts as main dev/build tool
> 
> What is pending:
> - Use vuex for vue state management
> - Order management views.
> - Ship it.
> 
> [image: mobile-paper-protoype]
> https://cloud.githubusercontent.com/assets/829971/14882596/d22284b2-0d39-11e6-8cd5-53f5bd66bb66.jpg
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/esclapes/esclapes.github.com/issues/2#issuecomment-215376164

## 

https://judithjanssen.es
www.paraembarazadas.es

**Comment by esclapes** [comment]
My own portfolio page:

What I learn:
- overcome the fear of exposure :)
- making [gif screencast](http://askubuntu.com/a/123515/497672) and using xwininfo

**Comment by esclapes** [comment]
Projects @ UNICF Spain
- 2010 ecommerce for corporate clients:
  - digital products ideation and definition, some of them still in use and with very similar workflows.
  - first balsamiq mockups
  - first big project managing a third party webdev team
  - first CRM integration. No real webservice yet, but we started to feel the need there.
- 2011 brand site redesign:
  - first (really) big project:
  - many stakeholders and different external providers
  - in depth SEO optimization
  - in-house training to different departments
- 2013 campaign (Ahora no podemos parar)
  - first responsive web site
  - first multi-step donation and pledge funnels
- 2014-2015 behind the scenes
  - definition of first web service to connect with the CRM
  - refactoring of payment gateway modules (PHP/drupal)
  - refactoring of deploy scripts (bash scripts)
  - Google Analytics implementation (event and conversion conversion tracking)

**Comment by esclapes** [comment]
Conversion optimization at UNICEF (form evolution)

![ayudanos a salvar la vida de muchos ninos hazte socio unicef comite espanol](https://cloud.githubusercontent.com/assets/829971/14897521/99a64576-0d82-11e6-9ded-989efd63b96b.png)
![hacer una donacion unicef espana](https://cloud.githubusercontent.com/assets/829971/14897522/99ace764-0d82-11e6-8e4a-9ad557e9753c.png)
![unicef comite espanol](https://cloud.githubusercontent.com/assets/829971/14897523/99b0c8c0-0d82-11e6-9402-3dcb97e70c12.png)
